# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gc < Formula
  desc "GitCode CLI - Command line tool for GitCode"
  homepage "https://gitcode.com/gitcode-cli/cli"
  version "0.11.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.11.1/gc_0.11.1_darwin_amd64.tar.gz"
      sha256 "4ee0089edcbf657c5c66766ef61362b9a8c62de72579ecf5abd9cc6f4ac89ea2"

      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.11.1/gc_0.11.1_darwin_arm64.tar.gz"
      sha256 "0300b7f9fea6bf8a7f255614dfaf608527e56a8409a19544fcbc6fa343cf3d73"

      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.11.1/gc_0.11.1_linux_amd64.tar.gz"
      sha256 "b7ad22cff96b35f768b5bd4d56d6c29613bd549698b61b00c34b1d35059c5071"
      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.11.1/gc_0.11.1_linux_arm64.tar.gz"
      sha256 "d7dd7bee1c9b8fd811c80fe22eec24230a0611d339e688b22db43acaf4bf501c"
      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  test do
    assert_match "gc version", shell_output("#{bin}/gc version")
    assert_match "gitcode version", shell_output("#{bin}/gitcode version")
  end
end
