# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gc < Formula
  desc "GitCode CLI - Command line tool for GitCode"
  homepage "https://gitcode.com/gitcode-cli/cli"
  version "0.10.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.10.3/gc_0.10.3_darwin_amd64.tar.gz"
      sha256 "dd9adbbf72d1ebe6560904dc55e64c2ad0520c4ee1cc3fe9a774e4ac2a51ae9c"

      define_method(:install) do
        bin.install "gc"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.10.3/gc_0.10.3_darwin_arm64.tar.gz"
      sha256 "e32d311e23c7283180be314f868d7e5ffb56aef5f8a8344d4570ecac8d0f996e"

      define_method(:install) do
        bin.install "gc"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.10.3/gc_0.10.3_linux_amd64.tar.gz"
      sha256 "a1cc8ed543ef3fdb648dc2d54d4f2e011cba8942fed8eb17807f17293bc1b5c6"
      define_method(:install) do
        bin.install "gc"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.10.3/gc_0.10.3_linux_arm64.tar.gz"
      sha256 "ac39645a2ecfc6b126458b065e3a379ae19926705cca12211daa7bd10a2a73af"
      define_method(:install) do
        bin.install "gc"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  test do
    assert_match "gc version", shell_output("#{bin}/gc version")
  end
end
