# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gc < Formula
  desc "GitCode CLI - Command line tool for GitCode"
  homepage "https://gitcode.com/gitcode-cli/cli"
  version "0.13.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.13.0/gc_0.13.0_darwin_amd64.tar.gz"
      sha256 "bf47ed3b1a8fdc297c4d006f020caa65667b3da7c24be6f461b9c7582c30ae65"

      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.13.0/gc_0.13.0_darwin_arm64.tar.gz"
      sha256 "5badc7e82df327b0e76be206c3e7f4e24daa64b560cabe209ce97d036a20843a"

      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.13.0/gc_0.13.0_linux_amd64.tar.gz"
      sha256 "0b5a278e2da07815df4c13ecaf441f780bd6ad65cfe13c8ac7482d86fecafe03"
      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/gitcode-cli/cli/releases/download/v0.13.0/gc_0.13.0_linux_arm64.tar.gz"
      sha256 "87e70d237da48fb3d9e4177aea0090cf75106db175b9a97bb38d29dc9903f35d"
      define_method(:install) do
        bin.install "gc"
        bin.install_symlink "gc" => "gitcode"
        bash_completion.install "completions/gc.bash" => "gc"
        zsh_completion.install "completions/gc.zsh" => "_gc"
        fish_completion.install "completions/gc.fish"
      end
    end
  end

  test do
    assert_match "gc version", shell_output("#{bin}/gc version")
    assert_match "gitcode version", shell_output("#{bin}/gitcode version")
  end
end
